### ISSUE TITLE
Too many non-words

### ISSUE THREAD

**Issue by annam002** [bennorichters/bnoggles#29]
For English, there are a lot of short words that are not really words. Like “st“ or “sri“. This makes it really hard to find all the words.

**Comment by bennorichters** [comment]
Hi Anna, thanks for thinking along! It's all a matter of choices here. Those words can for instance be found here https://en.wikibooks.org/wiki/Scrabble/Two_Letter_Words and here https://www.wordfind.com/3-letter-words/ . I don't say those sources are above debate, but I am a little bit afraid it is hard to reach a consensus here.

Do you have any suggestions on how to improve the dictionary (not only regarding those two words of course)?

**Comment by annam002** [comment]
IMHO, it doesn't make sense to include these words, because it takes fun out of the game. You now end up sliding really quickly and just trying all the combinations, instead of actually trying to find “real“ words. For scrabble it makes sense to increase the number of combinations, but this game works differently.

**Comment by bennorichters** [comment]
OK, fair enough, I'll try to only include more sensible words
