### ISSUE TITLE
Show board on results screen

### ISSUE THREAD

**Issue by rspilker** [bennorichters/bnoggles#5]
When scrolling though the list of possible words, I would like to see the board I've been playing.

If possible, when a word is selected, highlight it on the board, preferably using arrows or animation to show the full path, not just the letters used.

**Comment by bennorichters** [comment]
The board is shown now. This issue still needs to be worked on. The layout is not nice and I am planning to implement the "select a word and show" feature as well.

**Comment by bennorichters** [comment]
@rspilker do you think the current situation is enough for an 'MVP'?

**Comment by bennorichters** [comment]
The animated result screen is on the backlog
